### ISSUE TITLE
Broken on Vagrant 1.0.3 / vagrant-list 0.0.1

### ISSUE THREAD

**Issue by foxx** [joshmcarthur/vagrant-list#1]
```

 root@envprov1 [/mnt/ds1/vagrant/projects/pm2] > VAGRANT_LOG=DEBUG vagrant list
 INFO global: Vagrant version: 1.0.3
 INFO vagrant: `vagrant` invoked: ["list"]
DEBUG vagrant: Creating Vagrant environment
 INFO environment: Environment initialized (#<Vagrant::Environment:0x0000000195e588>)
 INFO environment:   - cwd: /mnt/ds1/vagrant/projects/pm2
 INFO environment: Home path: /root/.vagrant.d
 INFO plugin: Searching and loading any available plugins...
 INFO plugin: Loading plugin: vagrant-list (0.0.1)
 INFO plugin: Loaded 1 plugins.
DEBUG vagrant: Loading environment
 INFO environment: Loading configuration...
DEBUG loader: Set :default = "/opt/vagrant/embedded/gems/gems/vagrant-1.0.3/config/default.rb"
DEBUG loader: Populating proc cache for "/opt/vagrant/embedded/gems/gems/vagrant-1.0.3/config/default.rb"
DEBUG loader: Load procs for pathname: #<Pathname:/opt/vagrant/embedded/gems/gems/vagrant-1.0.3/config/default.rb>
DEBUG loader: Set :root = #<Pathname:/mnt/ds1/vagrant/projects/pm2/Vagrantfile>
DEBUG loader: Populating proc cache for #<Pathname:/mnt/ds1/vagrant/projects/pm2/Vagrantfile>
DEBUG loader: Load procs for pathname: #<Pathname:/mnt/ds1/vagrant/projects/pm2/Vagrantfile>
DEBUG loader: Loading configuration in order: [:default, :box, :home, :root, :vm]
DEBUG loader: Loading from: default (evaluating)
DEBUG loader: Loading from: root (evaluating)
DEBUG loader: Configuration loaded successfully
DEBUG environment: Loading configuration for VM: prodclone1
DEBUG loader: Set :default = "/opt/vagrant/embedded/gems/gems/vagrant-1.0.3/config/default.rb"
DEBUG loader: Set :root = #<Pathname:/mnt/ds1/vagrant/projects/pm2/Vagrantfile>
DEBUG loader: Set :vm = [#<Proc:0x00000001953070@/mnt/ds1/vagrant/projects/pm2/Vagrantfile:7>]
DEBUG loader: Populating proc cache for #<Proc:0x00000001953070@/mnt/ds1/vagrant/projects/pm2/Vagrantfile:7>
DEBUG loader: Loading configuration in order: [:default, :box, :home, :root, :vm]
DEBUG loader: Loading from: default (cache)
DEBUG loader: Loading from: root (cache)
DEBUG loader: Loading from: vm (evaluating)
DEBUG provisioner: Provisioner config: shell
 INFO provisioner: Provisioner class: Vagrant::Provisioners::Shell
DEBUG provisioner: Configuring provisioner with: Vagrant::Provisioners::Shell::Config
DEBUG loader: Configuration loaded successfully
DEBUG loader: Set :default = "/opt/vagrant/embedded/gems/gems/vagrant-1.0.3/config/default.rb"
DEBUG loader: Set :box = #<Pathname:/root/.vagrant.d/boxes/precise64/Vagrantfile>
DEBUG loader: Populating proc cache for #<Pathname:/root/.vagrant.d/boxes/precise64/Vagrantfile>
DEBUG loader: Load procs for pathname: #<Pathname:/root/.vagrant.d/boxes/precise64/Vagrantfile>
DEBUG loader: Set :root = #<Pathname:/mnt/ds1/vagrant/projects/pm2/Vagrantfile>
DEBUG loader: Set :vm = [#<Proc:0x00000001953070@/mnt/ds1/vagrant/projects/pm2/Vagrantfile:7>]
DEBUG loader: Loading configuration in order: [:default, :box, :home, :root, :vm]
DEBUG loader: Loading from: default (cache)
DEBUG loader: Loading from: box (evaluating)
DEBUG loader: Loading from: root (cache)
DEBUG loader: Loading from: vm (cache)
DEBUG loader: Configuration loaded successfully
DEBUG environment: Loading configuration for VM: slice21
DEBUG loader: Set :default = "/opt/vagrant/embedded/gems/gems/vagrant-1.0.3/config/default.rb"
DEBUG loader: Set :root = #<Pathname:/mnt/ds1/vagrant/projects/pm2/Vagrantfile>
DEBUG loader: Set :vm = [#<Proc:0x000000019525a8@/mnt/ds1/vagrant/projects/pm2/Vagrantfile:16>]
DEBUG loader: Populating proc cache for #<Proc:0x000000019525a8@/mnt/ds1/vagrant/projects/pm2/Vagrantfile:16>
DEBUG loader: Loading configuration in order: [:default, :box, :home, :root, :vm]
DEBUG loader: Loading from: default (cache)
DEBUG loader: Loading from: box (cache)
DEBUG loader: Loading from: root (cache)
DEBUG loader: Loading from: vm (evaluating)
DEBUG provisioner: Provisioner config: shell
 INFO provisioner: Provisioner class: Vagrant::Provisioners::Shell
DEBUG provisioner: Configuring provisioner with: Vagrant::Provisioners::Shell::Config
DEBUG loader: Configuration loaded successfully
DEBUG loader: Set :default = "/opt/vagrant/embedded/gems/gems/vagrant-1.0.3/config/default.rb"
DEBUG loader: Set :box = #<Pathname:/root/.vagrant.d/boxes/precise64/Vagrantfile>
DEBUG loader: Set :root = #<Pathname:/mnt/ds1/vagrant/projects/pm2/Vagrantfile>
DEBUG loader: Set :vm = [#<Proc:0x000000019525a8@/mnt/ds1/vagrant/projects/pm2/Vagrantfile:16>]
DEBUG loader: Loading configuration in order: [:default, :box, :home, :root, :vm]
DEBUG loader: Loading from: default (cache)
DEBUG loader: Loading from: box (cache)
DEBUG loader: Loading from: root (cache)
DEBUG loader: Loading from: vm (cache)
DEBUG loader: Configuration loaded successfully
 INFO cli: CLI: [] "list" []
DEBUG cli: Invoking command class: Vagrant::List::All []
 INFO virtualbox_base: VBoxManage path: VBoxManage
 INFO subprocess: Starting process: ["VBoxManage", "--version"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: 4.1.20r80170

DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG virtualbox: Finding driver for VirtualBox version: 4.1.20
 INFO virtualbox: Using VirtualBox driver: Vagrant::Driver::VirtualBox_4_1
 INFO virtualbox_base: VBoxManage path: VBoxManage
 INFO subprocess: Starting process: ["VBoxManage", "list", "vms"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: "<inaccessible>" {80af4d80-e4bd-4fe2-8866-3d3a05290375}
"lucid64upgrade_1346412824" {432a349c-c17b-4be8-9423-62778f2416a6}
"precise64upgrade_1346413097" {9e09b7d7-81e2-45a2-b877-da1862120f96}
"pm2_1346671118" {30ed0c7d-df54-4eb4-8db9-7ecb3adf09be}

DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO interface: info: ALL:
[vagrant] ALL:
 INFO virtualbox_base: VBoxManage path: VBoxManage
 INFO subprocess: Starting process: ["VBoxManage", "--version"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: 4.1.20r80170

DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG virtualbox: Finding driver for VirtualBox version: 4.1.20
 INFO virtualbox: Using VirtualBox driver: Vagrant::Driver::VirtualBox_4_1
 INFO virtualbox_base: VBoxManage path: VBoxManage
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "80af4d80-e4bd-4fe2-8866-3d3a05290375"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: VBoxManage: error: Runtime error opening '/root/VirtualBox VMs/ds1_1346358415/ds1_1346358415.vbox' for reading: -102 (File not found.).
VBoxManage: error: /home/vbox/vbox-4.1.20/src/VBox/Main/src-server/MachineImpl.cpp[708] (nsresult Machine::registeredInit())
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component VirtualBox, interface IVirtualBox, callee

DEBUG subprocess: stdout: Name:            <inaccessible!>
UUID:            80af4d80-e4bd-4fe2-8866-3d3a05290375
Config file:     /root/VirtualBox VMs/ds1_1346358415/ds1_1346358415.vbox
Access error details:


DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO virtualbox: VBoxManage error text found, assuming error.
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::VBoxManageError: There was an error executing the following command with VBoxManage:

["showvminfo", "80af4d80-e4bd-4fe2-8866-3d3a05290375"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.>
ERROR vagrant: There was an error executing the following command with VBoxManage:

["showvminfo", "80af4d80-e4bd-4fe2-8866-3d3a05290375"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.0.3/lib/vagrant/driver/virtualbox_base.rb:286:in `block in execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.3/lib/vagrant/util/retryable.rb:14:in `retryable'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.3/lib/vagrant/driver/virtualbox_base.rb:268:in `execute'
/root/.vagrant.d/gems/gems/vagrant-list-0.0.1/lib/vagrant/vm_info.rb:12:in `initialize'
/root/.vagrant.d/gems/gems/vagrant-list-0.0.1/lib/vagrant-list.rb:13:in `new'
/root/.vagrant.d/gems/gems/vagrant-list-0.0.1/lib/vagrant-list.rb:13:in `block in execute'
/root/.vagrant.d/gems/gems/vagrant-list-0.0.1/lib/vagrant-list.rb:12:in `each'
/root/.vagrant.d/gems/gems/vagrant-list-0.0.1/lib/vagrant-list.rb:12:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.3/lib/vagrant/cli.rb:42:in `execute'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.3/lib/vagrant/environment.rb:167:in `cli'
/opt/vagrant/embedded/gems/gems/vagrant-1.0.3/bin/vagrant:43:in `<top (required)>'
/opt/vagrant/bin/../embedded/gems/bin/vagrant:19:in `load'
/opt/vagrant/bin/../embedded/gems/bin/vagrant:19:in `<main>'
 INFO interface: error: There was an error executing the following command with VBoxManage:

["showvminfo", "80af4d80-e4bd-4fe2-8866-3d3a05290375"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
There was an error executing the following command with VBoxManage:

["showvminfo", "80af4d80-e4bd-4fe2-8866-3d3a05290375"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
```

I have absolutely no experience with Ruby, so I can't offer much other diagnostic other than this dump :/

Cal

**Comment by joshmcarthur** [comment]
Don't worry @foxx, I can see where the error is - I'll have a fix out for you shortly :-)

**Comment by joshmcarthur** [comment]
Hey @foxx - I've just pushed a fix for this. See if `0.0.3` works for you :-)

**Comment by foxx** [comment]
Hey @joshmcarthur - ill give that a shot - thanks for the fast reply!

**Comment by joshmcarthur** [comment]
No problem. Feel free to close this if it works for you, or comment back here if it doesn't

**Comment by joshmcarthur** [comment]
Closing, since it's been a month since last post. Please post a new issue if you're still having problems!
