### ISSUE TITLE
wrong number of arguments: 1 for 0

### ISSUE THREAD

**Issue by llimllib** [joshmcarthur/vagrant-list#2]
```
$ sudo gem install vagrant-list
Password:
Building native extensions.  This could take a while...
Building native extensions.  This could take a while...
Successfully installed archive-tar-minitar-0.5.2
Successfully installed ffi-1.1.5
Successfully installed childprocess-0.3.5
Successfully installed json-1.5.4
Successfully installed net-scp-1.0.4
Successfully installed vagrant-1.0.5
Successfully installed vagrant-list-0.0.3
7 gems installed
Installing ri documentation for archive-tar-minitar-0.5.2...
Installing ri documentation for ffi-1.1.5...
Installing ri documentation for childprocess-0.3.5...
Installing ri documentation for json-1.5.4...
Installing ri documentation for net-scp-1.0.4...
Installing ri documentation for vagrant-1.0.5...
Installing ri documentation for vagrant-list-0.0.3...
Installing RDoc documentation for archive-tar-minitar-0.5.2...
Installing RDoc documentation for ffi-1.1.5...
Installing RDoc documentation for childprocess-0.3.5...
Installing RDoc documentation for json-1.5.4...
Installing RDoc documentation for net-scp-1.0.4...
Installing RDoc documentation for vagrant-1.0.5...
Installing RDoc documentation for vagrant-list-0.0.3...

$ vagrant list
/Library/Ruby/Gems/1.8/gems/vagrant-list-0.0.3/lib/vagrant-list.rb:11:in `execute': wrong number of arguments (1 for 0) (ArgumentError)
    from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.5/lib/vagrant/cli.rb:42:in `execute'
    from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.5/lib/vagrant/environment.rb:167:in `cli'
    from /Library/Ruby/Gems/1.8/gems/vagrant-1.0.5/bin/vagrant:43
    from /usr/bin/vagrant:19:in `load'
    from /usr/bin/vagrant:19

$ vagrant -v
Vagrant version 1.0.5
```

Any ideas?

I'm not sure why it installed vagrant, I already had it installed.

**Comment by joshmcarthur** [comment]
Hi @llimllib, sorry it took a while for me to get to this.

I think this was happening because I hadn't added support for Vagrant's VirtualBox 4.2 driver, so not all the code I required was being loaded into the driver class. In the release I've just done, `0.0.4`, I've:

a) Rescued from commands failing so that a friendlier error message is shown than the one above
b) Loaded required code into drivers for VirtualBox versions 4.1 AND 4.2

Try updating to `0.0.4` and see if it helps at all.

**Comment by llimllib** [comment]
Worked great, thanks for the timely response

```
$ sudo gem install vagrant-list
Password:
Successfully installed vagrant-list-0.0.4
1 gem installed
Installing ri documentation for vagrant-list-0.0.4...
Installing RDoc documentation for vagrant-list-0.0.4...

$ vagrant list
[vagrant] ALL:
[vagrant] 085a532e-7a3a-4403-bcd4-91c17ae27de9: 'v-root', Host path (Ubuntu (64 bit))
[vagrant] 8452dedf-17a6-4bd4-92b8-ed6ce84adf98: 'v-root', Host path (Ubuntu (64 bit))
[vagrant] RUNNING:
```
