### ISSUE TITLE
Windows host not supported

### ISSUE THREAD

**Issue by InPermutation** [joshmcarthur/vagrant-list#6]
```
PS C:\> vagrant plugin install vagrant-list
Installing the 'vagrant-list' plugin. This can take a few minutes...
Installed the plugin 'vagrant-list (0.0.6)'!
PS C:\> vagrant list
ALL:
C:/Users/jacob/.vagrant.d/gems/gems/vagrant-list-0.0.6/lib/vagrant-list/virtual_box/list.rb:7:in ``': No such file or directory - VBoxManage list vms (Errno::ENOENT)
    from C:/Users/jacob/.vagrant.d/gems/gems/vagrant-list-0.0.6/lib/vagrant-list/virtual_box/list.rb:7:in `all'
    from C:/Users/jacob/.vagrant.d/gems/gems/vagrant-list-0.0.6/lib/vagrant-list/command.rb:8:in `execute'
    from C:/Vagrant/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/cli.rb:46:in `execute'
    from C:/Vagrant/Vagrant/embedded/gems/gems/vagrant-1.2.2/lib/vagrant/environment.rb:467:in `cli'
    from C:/Vagrant/Vagrant/embedded/gems/gems/vagrant-1.2.2/bin/vagrant:84:in `<top (required)>'
    from C:/Vagrant/Vagrant/bin//../embedded/../embedded/gems/bin/vagrant:23:in `load'
    from C:/Vagrant/Vagrant/bin//../embedded/../embedded/gems/bin/vagrant:23:in `<main>'
```

**Comment by InPermutation** [comment]
The problem is that `VBoxManage` is not on PATH:

```
PS C:\> $env:PATH="$env:PATH;C:\Program Files\Oracle\VirtualBox"
PS C:\> vagrant list
ALL:
2be9773e-fb52-433e-8f3d-281046d04039: vagrant_1367528616 (Ubuntu (64 bit))
b0c28b16-1ba9-4b0c-84f9-70b7c2c75e24: vagrant_1367955585 (Ubuntu (64 bit))
64cd95ff-1b76-4d45-81cb-633438fff7d1: vagrant_1368455355 (Ubuntu (64 bit))
RUNNING:
64cd95ff-1b76-4d45-81cb-633438fff7d1: vagrant_1368455355 (Ubuntu (64 bit))
PS C:\>
```

**Comment by joshmcarthur** [comment]
@krallja I'm somewhat reluctant to mess with your path to fix this - would you feel that an adequate resolution to this issue would be to add some help regarding the problem you experienced to the README?

**Comment by joshmcarthur** [comment]
Thanks for the pull request!
